### ISSUE TITLE
neurojs is not defined

### ISSUE THREAD

**Issue by samfultonjr** [janhuenermann/neurojs#14]
I am trying to run the cars example. I ran npm install and then npm start. But when I go into the console of the page it says neurojs is not defined. It is trying to find a file called build/neurojs-v2.js and that just doesn't exist. Not quite sure why...

**Comment by janhuenermann** [comment]
Thanks for the issue. Yea, I'm currently in the process of "refreshing" the car example and the framework (in the long-term I want to do a rewrite, but right now just want to tweak it so it converges more consistently). The issue can easily be resolved by running `webpack` in the root dir of the repo. This is just a temporary fix, as I will try to make it work so webpack-dev-server (aka `npm run start`) does this. Will push a fix soon.

**Comment by samfultonjr** [comment]
Sounds good, thanks for your hard work! @janhuenermann
