### ISSUE TITLE
Drive into a dead end way, the car can't back out.

### ISSUE THREAD

**Issue by mztest** [janhuenermann/neurojs#2]
Drive into a dead end way, the car can't back out.

![2017-02-28 16 01 33](https://cloud.githubusercontent.com/assets/323810/23396539/3c0ac458-fdcf-11e6-9839-45720759b740.png)

**Comment by janhuenermann** [comment]
Please only post issues with the framework and not with the performance of the algorithm. Thanks!

Edit: improvement suggestions to the algorithm are obviously welcome

**Comment by js08** [comment]
@janhuenermann so what algorithm are using for this application??
