### ISSUE TITLE
How to debug the Process

### ISSUE THREAD

**Issue by nellaivijay** [janhuenermann/neurojs#3]
Hi,
How can we debug the learning process and metrics of the RL Network to get the understand about the process. 

Thanks
Vijay

**Comment by janhuenermann** [comment]
Hi, 

didn't have time to write a documentation, maybe I'll do that in the future. But for now, can you please elaborate on what exactly you want to measure. The network loss? The current reward? 

If you mean the car demo, then the chart at the bottom of the page will contain this information. 
(Black line = loss, lighter-green line = current reward, darker-green line = smooth reward)

Jan
