### ISSUE TITLE
Add live browser demo

### ISSUE THREAD

**Issue by danfinlay** [janhuenermann/neurojs#4]
While you're using browser tech, why not link to a working build?  Github pages is great for this.

**Comment by ahmetkakici** [comment]
@flyswatter here is a live demo; http://janhuenermann.com/projects/learning-to-drive

**Comment by q2dg** [comment]
When I draw an obstacle, cars get stuck in front of it but they doesn't resume their walk

**Comment by lingsamuel** [comment]
Their moving directions cannot be reversed so they just stuck in front of walls.

**Comment by janhuenermann** [comment]
Yes I agree with @ahmetkakici. We already have a live a demo. The problem with Github pages is, that you can't load any pre-trained agents, because you simply don't have the files/checkpoints.

**Comment by danfinlay** [comment]
Ok, thanks!
