### ISSUE TITLE
car stuck

### ISSUE THREAD

**Issue by js08** [janhuenermann/neurojs#8]
![screen shot 2017-02-28 at 8 08 03 pm](https://cloud.githubusercontent.com/assets/1699943/23488679/cf36a082-feb3-11e6-8a53-7e6e63bf2b27.png)

**Comment by janhuenermann** [comment]
Yes the problem is with the physics library, I think. You can improve the physics world parameters (tolerance, iterations, stiffness, relaxation in world.js) so that this will occur less frequently, but probably will be hard to solve 100%. I don't see a too big of an issue right now, because it happens quite rarely.

**Comment by landsman** [comment]
I hope the AI will still learning 


[![bug](https://img.youtube.com/vi/HhnrN7r-Weg/0.jpg)](https://www.youtube.com/watch?v=HhnrN7r-Weg)

**Comment by janhuenermann** [comment]
The AI is not learning on that page. Please read the project page before posting something like that here.

"Note however, that the demo you see above doesn't train the neural networks, therefore they are not learning (this is done offline)."

**Comment by landsman** [comment]
Oh sorry.
I was think that is for public research.
http://www.czechcrunch.cz/2017/02/17lety-programator-vytvoril-online-projekt-ktery-umi-postupne-ucit-samoriditelna-auta/

**Comment by js08** [comment]
@janhuenermann I looked at the code but not sure how to solve...any idea how to solve https://github.com/janhuenermann/neurojs/blob/05c0721dab8ea65b13551a2f6df72c1ecae11d04/examples/cars/src/world.js

**Comment by janhuenermann** [comment]
@js08 I figured it out, I think. Has something to do with CCD (continuous collision detection) of physics lib. Apparently wasn't turned on. Going to commit fix soon.

**Comment by js08** [comment]
@janhuenermann hello where you able to commit the code

**Comment by janhuenermann** [comment]
Yes, take a look at the `experimental` branch.
